#!/bin/bash
sudo hostnamectl set-hostname ci
sudo yum -y install unzip wget tree git
sudo yum install java-11-openjdk -y
sudo wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo
sudo rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
sudo yum -y install jenkins  --nobest
sudo systemctl start jenkins
sudo systemctl enable jenkins
sudo systemctl status jenkins
